### ISSUE TITLE
[ChangeRequestForm]Defect - “Show Total Cash Held” is not being reset after collected all the money from the machine

### ISSUE THREAD

**Issue by Michael-NUS** [nyinyizin/cmca-vmcs#1]
Change Request#: VMCS/CR/2017/0001
[ChangeRequestForm_Defect_TeamPT7.docx](https://github.com/nyinyizin/cmca-vmcs/files/1287241/ChangeRequestForm_Defect_TeamPT7.docx)

**Comment by nyinyizin** [comment]
@Michael-NUS issue#1 (bug) had been fixed and the [pull request](https://github.com/nyinyizin/cmca-vmcs/pull/3) had been submitted to merge

**Comment by nyinyizin** [comment]
@Michael-NUS Change Request#: VMCS/CR/2017/0001 have been updated.

[ChangeRequestForm_Defect_TeamPT7.docx](https://github.com/nyinyizin/cmca-vmcs/files/1289669/ChangeRequestForm_Defect_TeamPT7.docx)

And the bug has been fixed in [#3](https://github.com/nyinyizin/cmca-vmcs/pull/3) pull request.

**Comment by Michael-NUS** [comment]
Thanks Nyi, 
Approved the Change Request
[Approved_ChangeRequestForm_Defect_TeamPT7.docx](https://github.com/nyinyizin/cmca-vmcs/files/1289690/Approved_ChangeRequestForm_Defect_TeamPT7.docx)

**Comment by leon4one1747** [comment]
Defect CR approved
[APPROVED_ChangeRequestForm_Defect_TeamPT7.docx](https://github.com/nyinyizin/cmca-vmcs/files/1289712/APPROVED_ChangeRequestForm_Defect_TeamPT7.docx)

**Comment by nyinyizin** [comment]
the bug has been fixed [#3](https://github.com/nyinyizin/cmca-vmcs/pull/3)

**Comment by nyinyizin** [comment]
Merging done for enhancement [#3](https://github.com/nyinyizin/cmca-vmcs/pull/3)

**Comment by Michael-NUS** [comment]
Thanks for the development and validation from both the Technical and QA team.
The version: RC1.0.9 contains this defect fix.
I will proceed to close this CR
