### ISSUE TITLE
[ChangeRequest]Enhancement - Show the total value for each denomination

### ISSUE THREAD

**Issue by Michael-NUS** [nyinyizin/cmca-vmcs#2]
Change Request #: VMCS/CR/2017/0002

[ChangeRequestForm_Enhancement_TeamPT7.docx](https://github.com/nyinyizin/cmca-vmcs/files/1287237/ChangeRequestForm_Enhancement_TeamPT7.docx)

**Comment by aslin1126** [comment]
this is the updated ChangeRequestForm
[ChangeRequestForm_Enhancement_TeamPT7_09092017.docx](https://github.com/nyinyizin/cmca-vmcs/files/1289548/ChangeRequestForm_Enhancement_TeamPT7_09092017.docx)

**Comment by Michael-NUS** [comment]
Updated the Change Request Form;

[ChangeRequestForm_Enhancement_TeamPT7_09092017.docx](https://github.com/nyinyizin/cmca-vmcs/files/1289707/ChangeRequestForm_Enhancement_TeamPT7_09092017.docx)

**Comment by leon4one1747** [comment]
Enhancement CR approved
[APPROVED_ChangeRequestForm_Enhancement_TeamPT7_09092017.docx](https://github.com/nyinyizin/cmca-vmcs/files/1289711/APPROVED_ChangeRequestForm_Enhancement_TeamPT7_09092017.docx)

**Comment by aungmyo7** [comment]
Updated Design Model Report for this enhancement.

**Comment by aungmyo7** [comment]
Committed the updated Design Model Report under enhancement-rc1.0.9/doc

**Comment by nyinyizin** [comment]
Merging done for enhancement [#4](https://github.com/nyinyizin/cmca-vmcs/pull/4)

**Comment by Michael-NUS** [comment]
Thanks for the development and validation from both the Technical and QA team.
The version: RC1.0.9 contains this enhancement.
I will proceed to close this CR
